// <auto-generated />
using FizzBuzzAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FizzBuzzAPI.Migrations
{
    [DbContext(typeof(FizzBuzzDBContext))]
    partial class FizzBuzzDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("FizzBuzzAPI.Models.FizzBuzzStore", b =>
                {
                    b.Property<int>("FizzBuzzStoreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FizzBuzzValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FizzBuzzStoreID");

                    b.ToTable("FizzBuzzStoretbl");

                    b.HasData(
                        new
                        {
                            FizzBuzzStoreID = 1,
                            FizzBuzzValue = "1"
                        },
                        new
                        {
                            FizzBuzzStoreID = 2,
                            FizzBuzzValue = "2"
                        },
                        new
                        {
                            FizzBuzzStoreID = 3,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 4,
                            FizzBuzzValue = "4"
                        },
                        new
                        {
                            FizzBuzzStoreID = 5,
                            FizzBuzzValue = "Buzz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 6,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 7,
                            FizzBuzzValue = "7"
                        },
                        new
                        {
                            FizzBuzzStoreID = 8,
                            FizzBuzzValue = "8"
                        },
                        new
                        {
                            FizzBuzzStoreID = 9,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 10,
                            FizzBuzzValue = "Buzz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 11,
                            FizzBuzzValue = "11"
                        },
                        new
                        {
                            FizzBuzzStoreID = 12,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 13,
                            FizzBuzzValue = "13"
                        },
                        new
                        {
                            FizzBuzzStoreID = 14,
                            FizzBuzzValue = "14"
                        },
                        new
                        {
                            FizzBuzzStoreID = 15,
                            FizzBuzzValue = "FizzBuzz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 16,
                            FizzBuzzValue = "16"
                        },
                        new
                        {
                            FizzBuzzStoreID = 17,
                            FizzBuzzValue = "17"
                        },
                        new
                        {
                            FizzBuzzStoreID = 18,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 19,
                            FizzBuzzValue = "19"
                        },
                        new
                        {
                            FizzBuzzStoreID = 20,
                            FizzBuzzValue = "Buzz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 21,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 22,
                            FizzBuzzValue = "22"
                        },
                        new
                        {
                            FizzBuzzStoreID = 23,
                            FizzBuzzValue = "23"
                        },
                        new
                        {
                            FizzBuzzStoreID = 24,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 25,
                            FizzBuzzValue = "Buzz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 26,
                            FizzBuzzValue = "26"
                        },
                        new
                        {
                            FizzBuzzStoreID = 27,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 28,
                            FizzBuzzValue = "28"
                        },
                        new
                        {
                            FizzBuzzStoreID = 29,
                            FizzBuzzValue = "29"
                        },
                        new
                        {
                            FizzBuzzStoreID = 30,
                            FizzBuzzValue = "FizzBuzz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 31,
                            FizzBuzzValue = "31"
                        },
                        new
                        {
                            FizzBuzzStoreID = 32,
                            FizzBuzzValue = "32"
                        },
                        new
                        {
                            FizzBuzzStoreID = 33,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 34,
                            FizzBuzzValue = "34"
                        },
                        new
                        {
                            FizzBuzzStoreID = 35,
                            FizzBuzzValue = "Buzz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 36,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 37,
                            FizzBuzzValue = "37"
                        },
                        new
                        {
                            FizzBuzzStoreID = 38,
                            FizzBuzzValue = "38"
                        },
                        new
                        {
                            FizzBuzzStoreID = 39,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 40,
                            FizzBuzzValue = "Buzz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 41,
                            FizzBuzzValue = "41"
                        },
                        new
                        {
                            FizzBuzzStoreID = 42,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 43,
                            FizzBuzzValue = "43"
                        },
                        new
                        {
                            FizzBuzzStoreID = 44,
                            FizzBuzzValue = "44"
                        },
                        new
                        {
                            FizzBuzzStoreID = 45,
                            FizzBuzzValue = "FizzBuzz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 46,
                            FizzBuzzValue = "46"
                        },
                        new
                        {
                            FizzBuzzStoreID = 47,
                            FizzBuzzValue = "47"
                        },
                        new
                        {
                            FizzBuzzStoreID = 48,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 49,
                            FizzBuzzValue = "49"
                        },
                        new
                        {
                            FizzBuzzStoreID = 50,
                            FizzBuzzValue = "Buzz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 51,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 52,
                            FizzBuzzValue = "52"
                        },
                        new
                        {
                            FizzBuzzStoreID = 53,
                            FizzBuzzValue = "53"
                        },
                        new
                        {
                            FizzBuzzStoreID = 54,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 55,
                            FizzBuzzValue = "Buzz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 56,
                            FizzBuzzValue = "56"
                        },
                        new
                        {
                            FizzBuzzStoreID = 57,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 58,
                            FizzBuzzValue = "58"
                        },
                        new
                        {
                            FizzBuzzStoreID = 59,
                            FizzBuzzValue = "59"
                        },
                        new
                        {
                            FizzBuzzStoreID = 60,
                            FizzBuzzValue = "FizzBuzz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 61,
                            FizzBuzzValue = "61"
                        },
                        new
                        {
                            FizzBuzzStoreID = 62,
                            FizzBuzzValue = "62"
                        },
                        new
                        {
                            FizzBuzzStoreID = 63,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 64,
                            FizzBuzzValue = "64"
                        },
                        new
                        {
                            FizzBuzzStoreID = 65,
                            FizzBuzzValue = "Buzz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 66,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 67,
                            FizzBuzzValue = "67"
                        },
                        new
                        {
                            FizzBuzzStoreID = 68,
                            FizzBuzzValue = "68"
                        },
                        new
                        {
                            FizzBuzzStoreID = 69,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 70,
                            FizzBuzzValue = "Buzz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 71,
                            FizzBuzzValue = "71"
                        },
                        new
                        {
                            FizzBuzzStoreID = 72,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 73,
                            FizzBuzzValue = "73"
                        },
                        new
                        {
                            FizzBuzzStoreID = 74,
                            FizzBuzzValue = "74"
                        },
                        new
                        {
                            FizzBuzzStoreID = 75,
                            FizzBuzzValue = "FizzBuzz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 76,
                            FizzBuzzValue = "76"
                        },
                        new
                        {
                            FizzBuzzStoreID = 77,
                            FizzBuzzValue = "77"
                        },
                        new
                        {
                            FizzBuzzStoreID = 78,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 79,
                            FizzBuzzValue = "79"
                        },
                        new
                        {
                            FizzBuzzStoreID = 80,
                            FizzBuzzValue = "Buzz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 81,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 82,
                            FizzBuzzValue = "82"
                        },
                        new
                        {
                            FizzBuzzStoreID = 83,
                            FizzBuzzValue = "83"
                        },
                        new
                        {
                            FizzBuzzStoreID = 84,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 85,
                            FizzBuzzValue = "Buzz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 86,
                            FizzBuzzValue = "86"
                        },
                        new
                        {
                            FizzBuzzStoreID = 87,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 88,
                            FizzBuzzValue = "88"
                        },
                        new
                        {
                            FizzBuzzStoreID = 89,
                            FizzBuzzValue = "89"
                        },
                        new
                        {
                            FizzBuzzStoreID = 90,
                            FizzBuzzValue = "FizzBuzz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 91,
                            FizzBuzzValue = "91"
                        },
                        new
                        {
                            FizzBuzzStoreID = 92,
                            FizzBuzzValue = "92"
                        },
                        new
                        {
                            FizzBuzzStoreID = 93,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 94,
                            FizzBuzzValue = "94"
                        },
                        new
                        {
                            FizzBuzzStoreID = 95,
                            FizzBuzzValue = "Buzz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 96,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 97,
                            FizzBuzzValue = "97"
                        },
                        new
                        {
                            FizzBuzzStoreID = 98,
                            FizzBuzzValue = "98"
                        },
                        new
                        {
                            FizzBuzzStoreID = 99,
                            FizzBuzzValue = "Fizz"
                        },
                        new
                        {
                            FizzBuzzStoreID = 100,
                            FizzBuzzValue = "Buzz"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
